*{box-sizing:border-box}
:root{--bg:#f6f8fc;--text:#132033;--muted:#64748b;--line:#e2e8f0;--blue:#2563eb;--blue-dark:#1d4ed8;--shadow:0 20px 50px rgba(15,23,42,.09);--radius:20px}
body{margin:0;font-family:Arial,Helvetica,sans-serif;background:var(--bg);color:var(--text)}
a{color:var(--blue-dark);text-decoration:none;font-weight:800}.topbar{min-height:76px;background:#fff;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:14px 28px;position:sticky;top:0;z-index:5}
.brand{display:flex;align-items:center;gap:12px}.brand__logo{width:42px;height:42px;border-radius:14px;background:linear-gradient(135deg,var(--blue),#38bdf8);color:#fff;display:flex;align-items:center;justify-content:center;font-weight:900;font-size:22px}
.brand b{display:block}.brand small{display:block;color:var(--muted);margin-top:2px}.topbar__actions{display:flex;align-items:center;gap:16px;flex-wrap:wrap}
.layout{width:min(1280px,94vw);margin:32px auto}.login-card{width:min(520px,94vw);margin:80px auto;background:#fff;border:1px solid var(--line);border-radius:var(--radius);box-shadow:var(--shadow);padding:28px}
.login-card h1,.page-head h1{margin:0 0 10px;font-size:34px;letter-spacing:-.03em}.login-card p,.page-head p{margin:0 0 22px;color:var(--muted);line-height:1.5}
label{display:grid;gap:7px;font-weight:800;color:#334155}input,select,textarea{width:100%;border:1px solid #cbd5e1;border-radius:14px;padding:12px 13px;font-size:16px;background:#fff;color:var(--text)}textarea{min-height:100px;resize:vertical}
.btn{border:0;border-radius:14px;background:var(--blue);color:#fff;font-weight:900;padding:12px 16px;cursor:pointer;display:inline-flex;align-items:center;justify-content:center}.btn--ghost{background:#eff6ff;color:var(--blue-dark)}
.hint{font-size:14px;margin-top:16px!important}.page-head{display:flex;align-items:flex-start;justify-content:space-between;gap:20px;margin-bottom:20px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:18px}
.stats div{background:#fff;border:1px solid var(--line);border-radius:18px;padding:18px;box-shadow:var(--shadow)}.stats small{color:var(--muted);display:block;margin-bottom:6px}.stats b{font-size:30px}
.filters{background:#fff;border:1px solid var(--line);border-radius:18px;padding:16px;box-shadow:var(--shadow);display:grid;grid-template-columns:220px 1fr 180px 180px;gap:14px;margin-bottom:18px}
.message{padding:12px 14px;border-radius:14px;margin-bottom:16px;font-weight:800}.message--error{background:#fee2e2;color:#991b1b}.message--ok{background:#dcfce7;color:#166534}
.table-card{background:#fff;border:1px solid var(--line);border-radius:var(--radius);box-shadow:var(--shadow);overflow:hidden}.table-scroll{overflow:auto}table{width:100%;border-collapse:collapse;min-width:980px}th,td{padding:13px 12px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}th{font-size:13px;text-transform:uppercase;letter-spacing:.04em;color:#64748b;background:#f8fafc}td{font-size:14px}
.status{display:inline-flex;border-radius:999px;padding:5px 9px;font-weight:900;font-size:12px;background:#e2e8f0;color:#334155;white-space:nowrap}.status[data-status="Новая заявка"]{background:#dbeafe;color:#1e40af}.status[data-status="В работе"]{background:#fef3c7;color:#92400e}.status[data-status="Оплачено"]{background:#dcfce7;color:#166534}.status[data-status="Отказ"]{background:#fee2e2;color:#991b1b}
.mini-btn{border:0;border-radius:11px;background:#eff6ff;color:#1d4ed8;font-weight:900;padding:8px 10px;cursor:pointer}.dialog{width:min(860px,94vw);border:0;border-radius:22px;box-shadow:0 35px 90px rgba(15,23,42,.25);padding:0}.dialog::backdrop{background:rgba(15,23,42,.55)}.dialog__content{padding:0;margin:0;background:#fff;border-radius:22px}.dialog__head{display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--line);padding:20px 22px}.dialog__head h2{margin:0;font-size:26px}.icon-btn{border:0;background:#f1f5f9;width:38px;height:38px;border-radius:50%;font-size:24px;cursor:pointer}
.dialog-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px;padding:18px 22px;border-bottom:1px solid var(--line)}.dialog-grid div{background:#f8fafc;border:1px solid var(--line);border-radius:14px;padding:12px}.dialog-grid small{display:block;color:var(--muted);margin-bottom:5px}.dialog-grid p{margin:0;line-height:1.5}.wide{grid-column:1/-1}.edit-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;padding:18px 22px}.dialog__actions{display:flex;justify-content:flex-end;gap:10px;border-top:1px solid var(--line);padding:18px 22px}
@media(max-width:900px){.page-head{display:block}.page-head .btn{margin-top:10px}.stats{grid-template-columns:repeat(2,1fr)}.filters{grid-template-columns:1fr}.dialog-grid,.edit-grid{grid-template-columns:1fr}.wide{grid-column:auto}}
